Added load testing scripts
etherspot/e2e-sdk-prime pull request #27
Opened 2023-12-06 06:13 UTC by Jineshdarjee

## Description:
1. Added the load testing scripts for Arka and Skandha.

## Newly Created Files and Modified Files:
* **New File:** test/specs/mainnet-api/arka/LoadTesting.spec.js
* **New File:** test/specs/mainnet-api/skandha/LoadTesting.spec.js
* **New File:** test/utils/Arka_CsvToDatabase.js
* **New File:** test/utils/Skandha_CsvToDatabase.js
* **Modified File:** package.json
* **Modified File:** .env

2023-12-27 11:24 UTC, Jineshdarjee commented
## Description:
Modified Skandha test cases.

## Newly Created Files and Modified Files:
- **Modified File:** package.json
- **Modified File:** test/specs/mainnet-api/skandha/goerli.spec.js
- **Modified File:** test/specs/mainnet-api/skandha/mumbai.spec.js

2023-12-29 09:03 UTC, IAmKio requested changes
Left a few comments that need to be addressed. Please remember that anything you write needs to be written in a universal way and not for your local machine.

2023-12-29 10:29 UTC, Jineshdarjee commented on .env
> +DB_DATABASE=_bd_database_
Modified the code

2023-12-29 11:13 UTC, Jineshdarjee commented on test/specs/mainnet-api/arka/LoadTesting.spec.js
> +      'C:/Users/admin/apache-jmeter-5.6.2/apache-jmeter-5.6.2/arka_summaryreport.csv';
We are performing the load testing from the local system using the JMeter tool. So paths of the file are saved in the local system only.
But now I have added both paths in the .env file.

2023-12-29 11:14 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/LoadTesting.spec.js
> +      'C:/Users/admin/apache-jmeter-5.6.2/apache-jmeter-5.6.2/skandha_summaryreport.csv';
We are performing the load testing from the local system using the JMeter tool. So paths of the file are saved in the local system only.
But now I have added both paths in the .env file.

2023-12-29 12:36 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
>  dotenv.config(); // init dotenv
Updated the code from all the test case files.

2023-12-29 12:47 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
>  import * as dotenv from 'dotenv';
Updated the code from all the test case files.

2023-12-29 13:14 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +          'The Etherspot Wallet Address is not displayed successfully.',
assert.fail accept a single string parameter only.
and however, all the console errors are captured in mochawesome report so we can track errors from the report.

2023-12-29 13:25 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +        assert.fail('The transaction of the batch is not clear correctly.');
assert.fail accept a single string parameter only.
and however, all the console errors are captured in mochawesome report so we can track errors from the report.

2023-12-29 13:25 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +          'The addition of transaction in the batch is not performed.',
assert.fail accept a single string parameter only.
and however, all the console errors are captured in mochawesome report so we can track errors from the report.

2023-12-29 13:26 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +        // Signature = op.signature;
Removed the code.

2023-12-29 13:26 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +          'The estimate transactions added to the batch and get the fee data for the UserOp is not performed.',
assert.fail accept a single string parameter only.
and however, all the console errors are captured in mochawesome report so we can track errors from the report.

2023-12-29 13:26 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +          assert.fail('Getting an error');
assert.fail accept a single string parameter only.
and however, all the console errors are captured in mochawesome report so we can track errors from the report.

2023-12-29 13:27 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +            assert.fail('The response is not getting correct.');
assert.fail accept a single string parameter only.
and however, all the console errors are captured in mochawesome report so we can track errors from the report.

2023-12-29 13:27 UTC, Jineshdarjee commented on test/specs/mainnet-api/skandha/goerli.spec.js
> +        assert.fail('Getting an error');
assert.fail accept a single string parameter only.
and however, all the console errors are captured in mochawesome report so we can track errors from the report.

2023-12-29 13:27 UTC, Jineshdarjee commented on test/utils/Arka_CsvToDatabase.js
> +dotenv.config(); // init dotenv
Updated the code

2023-12-29 14:16 UTC, Jineshdarjee commented on test/utils/Arka_CsvToDatabase.js
**Current Load Testing Flow:**
* Perform the load testing on JMeter in the local system.
* The CSV file is created/updated in the local system.
* Run the test case of load testing, So CSV File details will save in the database.

2024-01-04 16:04 UTC, ch4r10t33r requested changes
Filenames should be capitalised and the directories should/shouldn't contain "_".  Can we pls be consistent with naming conventions of files?

2024-01-08 09:01 UTC, closed without merging